# Generated by Django 6.0.1 on 2026-02-05 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_affichage', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('type_doc', models.CharField(choices=[('CV', 'Curriculum Vitae'), ('GUIDE', 'Guide de Stage'), ('ANNEXE', 'Autre Annexe')], max_length=10)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur_noga', models.CharField(max_length=10)),
                ('date_recherche', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntrepriseCible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.TextField()),
                ('statut', models.CharField(default='À traiter', max_length=50)),
                ('guide_joint', models.BooleanField(default=False)),
                ('cv_utilise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_envoyes', to='core.documentutilisateur')),
                ('recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recherche')),
            ],
        ),
    ]
