# Generated by Django 6.0.1 on 2026-02-05 19:47

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entreprisecible_secteur_activite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentutilisateur',
            name='fichier',
            field=models.FileField(upload_to='cv_storage/', validators=[core.models.validate_file]),
        ),
        migrations.AlterField(
            model_name='documentutilisateur',
            name='nom_affichage',
            field=models.CharField(default='Mon CV', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentutilisateur',
            name='type_doc',
            field=models.CharField(choices=[('CV', 'Curriculum Vitae'), ('GUIDE', 'Guide de Stage')], default='CV', max_length=10),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='secteur_noga',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse_physique', models.TextField(blank=True)),
                ('phrase_informatique', models.TextField(default="votre expertise dans le développement et l'innovation numérique")),
                ('phrase_banque', models.TextField(default="la rigueur et l'excellence de votre institution financière")),
                ('phrase_luxe', models.TextField(default="votre savoir-faire d'exception et votre rayonnement international")),
                ('phrase_generale', models.TextField(default='le dynamisme et les projets de votre entreprise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
