# Generated by Django 6.0.2 on 2026-02-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_documentutilisateur_fichier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='adresse_physique',
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='npa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='rue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
