# Generated by Django 6.0.2 on 2026-02-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profilutilisateur_adresse_physique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='nom_lm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='prenom_lm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='npa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='rue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
