# Generated by Django 6.0.2 on 2026-02-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profilutilisateur_nom_lm_profilutilisateur_prenom_lm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='email_lm',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
