# Generated by Django 6.0.2 on 2026-02-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profilutilisateur_email_lm'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='dernier_zip',
            field=models.FileField(blank=True, null=True, upload_to='zips_generes/'),
        ),
    ]
