# Generated by Django 6.0.2 on 2026-03-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profilutilisateur_dernier_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprisecible',
            name='email_valide',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entreprisecible',
            name='est_dans_paquet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentutilisateur',
            name='type_doc',
            field=models.CharField(choices=[('CV', 'Curriculum Vitae'), ('CERTIFICAT', 'Certificat de travail'), ('DIPLOME', 'Diplôme / Notes'), ('GUIDE', 'Guide de Stage'), ('AUTRE', 'Autre annexe')], default='CV', max_length=10),
        ),
    ]
