# Generated by Django 6.0.2 on 2026-03-18 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_entreprisecible_email_valide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprisecible',
            name='guide_joint',
        ),
        migrations.AddField(
            model_name='entreprisecible',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentutilisateur',
            name='type_doc',
            field=models.CharField(choices=[('CV', 'CV'), ('CERTIFICAT', 'Certificat'), ('DIPLOME', 'Diplôme'), ('GUIDE', 'Guide'), ('AUTRE', 'Autre')], default='CV', max_length=10),
        ),
        migrations.AlterField(
            model_name='entreprisecible',
            name='cv_utilise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_envoyes', to='core.documentutilisateur'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='secteur_noga',
            field=models.CharField(max_length=255),
        ),
    ]
