# Generated by Django 6.0.2 on 2026-03-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_entreprisecible_guide_joint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprisecible',
            name='numero_pack',
            field=models.IntegerField(default=0),
        ),
    ]
