# Generated by Django 6.0.2 on 2026-03-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_entreprisecible_numero_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentutilisateur',
            name='secteur_nom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
