# Generated by Django 6.0.1 on 2026-03-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_documentutilisateur_secteur_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentutilisateur',
            name='type_doc',
            field=models.CharField(choices=[('CV', 'CV'), ('CERTIFICAT', 'Certificat'), ('DIPLOME', 'Diplôme'), ('GUIDE', 'Guide'), ('PACK_LM', 'Pack Lettres de motivation'), ('AUTRE', 'Autre')], default='CV', max_length=10),
        ),
    ]
