# Generated by Django 6.0.1 on 2026-03-27 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_documentutilisateur_type_doc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprisecible',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entreprisecible',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entreprisecible',
            name='recherche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.recherche'),
        ),
        migrations.AlterUniqueTogether(
            name='entreprisecible',
            unique_together={('utilisateur', 'email')},
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
                ('secteurs', models.CharField(max_length=255)),
                ('nb_entreprises', models.IntegerField(default=0)),
                ('nb_doublons_evites', models.IntegerField(default=0)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_scan'],
            },
        ),
        migrations.AddField(
            model_name='entreprisecible',
            name='scan_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprises', to='core.scansession'),
        ),
    ]
