# Generated by Django 6.0.1 on 2026-04-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_drop_lmmapping_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentutilisateur',
            name='used_for_gmail',
            field=models.BooleanField(default=False),
        ),
    ]
