# Generated by Django 6.0.1 on 2026-04-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_documentutilisateur_used_for_gmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepriseReferentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sitg', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('raison_sociale', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code_noga', models.CharField(blank=True, default='', max_length=20)),
                ('adresse', models.TextField(blank=True, default='')),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code_noga'], name='core_entrep_code_no_b213a7_idx'), models.Index(fields=['email'], name='core_entrep_email_70dccd_idx')],
            },
        ),
    ]
