# Generated by Django 6.0.1 on 2026-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_entreprisereferentiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprisecible',
            name='brouillon_gmail_cree',
            field=models.BooleanField(default=False),
        ),
    ]
