# Generated by Django 6.0.1 on 2026-05-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_entreprisereferentiel_email_valide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprisecible',
            name='cv_utilise',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='dernier_zip',
        ),
    ]
